### ISSUE TITLE
Is jekyll seo tag compatible with ghpages?

### ISSUE THREAD

**Issue by balazsszilardtoth** [t-richards/jekyll-google-tag-manager#13]
Hi Tom,

I tried to install your plugin, but build fails with The tag `gtm` on line 2 in `_includes/head.html` is not a recognized Liquid tag.

Thanks for your kind support on this,

Brgds,

balazs

**Comment by t-richards** [comment]
Hi @balazsszilardtoth ,

GitHub pages does not support custom plugins. Please see #12 for additional details.

Thanks!
